config/routes.rb
Rails.application.routes.draw do
  resources :disciplines
  resources :classrooms
  resources :students
  resources :libraries
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discipline.rb
class Discipline < ApplicationRecord
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]

  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:Type, :Series, :Schedule, :Availability, :name)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_with(model: discipline, local: true) do |form| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Type %>
    <%= form.text_field :Type %>
  </div>

  <div class="field">
    <%= form.label :Series %>
    <%= form.number_field :Series %>
  </div>

  <div class="field">
    <%= form.label :Schedule %>
    <%= form.text_field :Schedule %>
  </div>

  <div class="field">
    <%= form.label :Availability %>
    <%= form.check_box :Availability %>
  </div>

  <div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplines</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Series</th>
      <th>Schedule</th>
      <th>Availability</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= discipline.Type %></td>
        <td><%= discipline.Series %></td>
        <td><%= discipline.Schedule %></td>
        <td><%= discipline.Availability %></td>
        <td><%= discipline.name %></td>
        <td><%= link_to 'Show', discipline %></td>
        <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
        <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discipline', new_discipline_path %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @discipline.Type %>
</p>

<p>
  <strong>Series:</strong>
  <%= @discipline.Series %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @discipline.Schedule %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @discipline.Availability %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @discipline.name %>
</p>

<%= link_to 'Edit', edit_discipline_path(@discipline) %> |
<%= link_to 'Back', disciplines_path %>