config/routes.rb
Rails.application.routes.draw do
  resources :disciplines
  resources :classrooms
  resources :students
  resources :libraries
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :Student
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:Book_Name, :Book_Code, :Availability, :Quantity, :Student_id)
    end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Book_Name %>
    <%= form.text_field :Book_Name %>
  </div>

  <div class="field">
    <%= form.label :Book_Code %>
    <%= form.number_field :Book_Code %>
  </div>

  <div class="field">
    <%= form.label :Availability %>
    <%= form.check_box :Availability %>
  </div>

  <div class="field">
    <%= form.label :Quantity %>
    <%= form.number_field :Quantity %>
  </div>

  <div class="field">
    <%= form.label :Student_id %>
    <%= form.text_field :Student_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Book name</th>
      <th>Book code</th>
      <th>Availability</th>
      <th>Quantity</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.Book_Name %></td>
        <td><%= library.Book_Code %></td>
        <td><%= library.Availability %></td>
        <td><%= library.Quantity %></td>
        <td><%= library.Student %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @library.Book_Name %>
</p>

<p>
  <strong>Book code:</strong>
  <%= @library.Book_Code %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @library.Availability %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @library.Quantity %>
</p>

<p>
  <strong>Student:</strong>
  <%= @library.Student %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>