config/routes.rb
Rails.application.routes.draw do
  resources :disciplines
  resources :classrooms
  resources :students
  resources :libraries
  resources :teachers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :Discipline
  belongs_to :Classroom
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:Name, :Workload, :Cpf, :Discipline_id, :Classroom_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Workload %>
    <%= form.number_field :Workload %>
  </div>

  <div class="field">
    <%= form.label :Cpf %>
    <%= form.text_field :Cpf %>
  </div>

  <div class="field">
    <%= form.label :Discipline_id %>
    <%= form.text_field :Discipline_id %>
  </div>

  <div class="field">
    <%= form.label :Classroom_id %>
    <%= form.text_field :Classroom_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Workload</th>
      <th>Cpf</th>
      <th>Discipline</th>
      <th>Classroom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.Name %></td>
        <td><%= teacher.Workload %></td>
        <td><%= teacher.Cpf %></td>
        <td><%= teacher.Discipline %></td>
        <td><%= teacher.Classroom %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.Name %>
</p>

<p>
  <strong>Workload:</strong>
  <%= @teacher.Workload %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @teacher.Cpf %>
</p>

<p>
  <strong>Discipline:</strong>
  <%= @teacher.Discipline %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @teacher.Classroom %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>